name: Test and Build from feature branch
on: 
  push:
    branches-ignore:
      - 'master'
jobs:
  test-and-build-feature-branch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        yarn install
    - name: Unit-Tests
      run: |
        yarn test
    - name: Build-Storybook
      run: |
        yarn build-storybook
        pwd
